spring:
  application:
    name: Amperly

  datasource:
    url: jdbc:mysql://localhost:3306/amperly_db
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true

server:
  port: 8080

app:
  jwt:
    
    secret: ${JWT_SECRET}
    # Milliseconds – yaha default 1 ghanta (3600000 ms)
    expiration: ${JWT_EXPIRATION}

nasa:
  api:
    url: https://power.launchpad.nasa.gov/api/temporal/daily/point

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
